Проект готов к проверке.
avalon-dev-j110/laboratornaya-rabota-no1-DenisFilichev pull request #1
Opened 2020-03-31 12:24 UTC by DenisFilichev

Код готов к проверке.

2020-04-02 06:21 UTC, KolosovKD requested changes

2020-04-02 06:21 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Main.java
> +            }
Эту логику надо убирать в класс Person.
Здесь вам должны быть доступны конструкторы класса и его метод, возвращающий полное имя. Таким образом из любого места программы вы можете создать новый объект Person и получить его полное имя не повторяя весь этот код заново и заново, а просто делая
Person person = new Person(...........);
System.out.println(person.getFullName());
Вызывая разные конструкторы в зависимости от наличия или отсутствия отчества, второго имени и т.д.

2020-04-02 06:21 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +        this.government = "УМВД №17";
В этом случае невозможно создать человека с другой датой рождения, или с другими паспортными данными.

2020-04-02 06:21 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +        fullName = lastName + " " + firstName + " " + middleName;
Если вы храните только полное имя, смена фамилии становится очень нетрифиальной задачей. Имя, фамилия, отчество и второе имя стоит хранить в отдельных полях, объединяя для получения полного имени в методе, который будет это полное имя возвращать.

2020-04-08 21:07 UTC, KolosovKD approved these changes
Принято.
Есть расхождение реализации с описанием, но все реализовано прилично и явно 
продемонстрировано владение необходимыми иснструментами.

2020-04-08 21:07 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
>  class Passport {
Содержимое класса не соответствует его описанию (в комментарии над классом). Предполагалось что класс **Passport** будет содержать больше полей.

2020-04-08 21:07 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
> +    private String secondName = null;
null является значением по умолчанию, поэтому здесь нет нужды явно присваивать null.

2020-04-08 21:08 UTC, merged

2020-04-12 17:16 UTC, konivex reviewed
Исправьте замечание.

2020-04-12 17:16 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
>  public class Person {
Потерялись методы `String getFullName()` и `String getAddress()`, которые требовались заданием, верните их.
Обращаю внимание, что метод `String getAddress()` должен возвращать именно строку.